-- Placeholder migration to match production migration history.
-- Version 20250102010101 exists on remote but was missing in this repo.
-- Intentionally empty: the schema changes already exist in production.
