/**
 * AI Usage Report Generator for Solara
 *
 * Queries the last 7 days of AI usage events from Supabase and generates
 * a markdown report showing:
 * - Hit vs miss counts by feature
 * - Average token usage on misses
 * - Estimated costs
 *
 * Usage:
 *   npx tsx scripts/ai-usage-report.ts
 *
 * Prerequisites:
 *   npm install -D tsx
 */

import { createClient } from "@supabase/supabase-js";
import { writeFileSync } from "fs";
import { join } from "path";

// Get Supabase credentials from environment
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error("Missing Supabase credentials in environment");
  console.error("Required: NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

// Create admin client
const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

type AiUsageRow = {
  feature_label: string;
  cache_status: "hit" | "miss";
  total_tokens: number;
  estimated_cost_usd: number;
  created_at: string;
};

type FeatureStats = {
  hitCount: number;
  missCount: number;
  totalCost: number;
  totalTokensOnMiss: number;
  avgTokensOnMiss: number;
  avgCostOnMiss: number;
};

async function generateReport() {
  console.log("Generating AI usage report for last 7 days...\n");

  // Calculate date 7 days ago
  const sevenDaysAgo = new Date();
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

  // Query ai_usage_events
  const { data, error } = await supabase
    .from("ai_usage_events")
    .select("feature_label, cache_status, total_tokens, estimated_cost_usd, created_at")
    .gte("created_at", sevenDaysAgo.toISOString())
    .order("created_at", { ascending: false });

  if (error) {
    console.error("Failed to fetch AI usage data:", error.message);
    process.exit(1);
  }

  if (!data || data.length === 0) {
    console.log("No AI usage data found for last 7 days.");
    console.log("Once you start using the app, data will appear here.\n");

    const emptyReport = `# AI Token Usage Audit

**Report Generated:** ${new Date().toISOString()}

**Period:** Last 7 days

## Summary

No AI usage data found. Start using Solara features to see token usage here.

---

*Generated by \`scripts/ai-usage-report.ts\`*
`;

    const reportPath = join(process.cwd(), "AI_TOKEN_AUDIT.md");
    writeFileSync(reportPath, emptyReport, "utf-8");
    console.log(`✓ Empty report written to: AI_TOKEN_AUDIT.md`);
    return;
  }

  // Group by feature_label
  const featureMap = new Map<string, FeatureStats>();

  for (const row of data as AiUsageRow[]) {
    const feature = row.feature_label;

    if (!featureMap.has(feature)) {
      featureMap.set(feature, {
        hitCount: 0,
        missCount: 0,
        totalCost: 0,
        totalTokensOnMiss: 0,
        avgTokensOnMiss: 0,
        avgCostOnMiss: 0,
      });
    }

    const stats = featureMap.get(feature)!;

    if (row.cache_status === "hit") {
      stats.hitCount++;
    } else {
      stats.missCount++;
      stats.totalCost += row.estimated_cost_usd;
      stats.totalTokensOnMiss += row.total_tokens;
    }
  }

  // Calculate averages
  for (const [feature, stats] of featureMap) {
    if (stats.missCount > 0) {
      stats.avgTokensOnMiss = Math.round(stats.totalTokensOnMiss / stats.missCount);
      stats.avgCostOnMiss = stats.totalCost / stats.missCount;
    }
  }

  // Calculate totals
  let totalHits = 0;
  let totalMisses = 0;
  let totalCost = 0;

  for (const stats of featureMap.values()) {
    totalHits += stats.hitCount;
    totalMisses += stats.missCount;
    totalCost += stats.totalCost;
  }

  const cacheHitRate = totalHits + totalMisses > 0
    ? ((totalHits / (totalHits + totalMisses)) * 100).toFixed(1)
    : "0.0";

  // Generate markdown report
  const reportLines: string[] = [];

  reportLines.push("# AI Token Usage Audit\n");
  reportLines.push(`**Report Generated:** ${new Date().toISOString()}\n`);
  reportLines.push(`**Period:** Last 7 days\n`);
  reportLines.push("## Summary\n");
  reportLines.push(`- **Total Requests:** ${totalHits + totalMisses}`);
  reportLines.push(`- **Cache Hits:** ${totalHits} (${cacheHitRate}%)`);
  reportLines.push(`- **Cache Misses:** ${totalMisses}`);
  reportLines.push(`- **Total Cost (7 days):** $${totalCost.toFixed(4)}`);
  reportLines.push(`- **Projected Monthly Cost:** $${(totalCost * 30 / 7).toFixed(2)}\n`);

  reportLines.push("## By Feature\n");
  reportLines.push("| Feature | Hits | Misses | Avg Tokens/Miss | Avg Cost/Miss | Total Cost (7d) |");
  reportLines.push("|---------|------|--------|-----------------|---------------|-----------------|");

  // Sort by total cost descending
  const sortedFeatures = Array.from(featureMap.entries()).sort(
    ([, a], [, b]) => b.totalCost - a.totalCost
  );

  for (const [feature, stats] of sortedFeatures) {
    const avgTokens = stats.avgTokensOnMiss > 0 ? stats.avgTokensOnMiss.toLocaleString() : "-";
    const avgCost = stats.avgCostOnMiss > 0 ? `$${stats.avgCostOnMiss.toFixed(4)}` : "-";
    const totalCost = `$${stats.totalCost.toFixed(4)}`;

    reportLines.push(
      `| ${feature} | ${stats.hitCount} | ${stats.missCount} | ${avgTokens} | ${avgCost} | ${totalCost} |`
    );
  }

  reportLines.push("\n## Cache Efficiency\n");
  reportLines.push(`**Overall Cache Hit Rate:** ${cacheHitRate}%\n`);

  for (const [feature, stats] of sortedFeatures) {
    const total = stats.hitCount + stats.missCount;
    const hitRate = total > 0 ? ((stats.hitCount / total) * 100).toFixed(1) : "0.0";
    reportLines.push(`- **${feature}:** ${hitRate}% (${stats.hitCount}/${total})`);
  }

  reportLines.push("\n---\n");
  reportLines.push("*Generated by `scripts/ai-usage-report.ts`*\n");

  const report = reportLines.join("\n");
  const reportPath = join(process.cwd(), "AI_TOKEN_AUDIT.md");

  writeFileSync(reportPath, report, "utf-8");

  console.log("✓ Report generated successfully!");
  console.log(`✓ Written to: AI_TOKEN_AUDIT.md\n`);
  console.log("Summary:");
  console.log(`  Total Requests: ${totalHits + totalMisses}`);
  console.log(`  Cache Hit Rate: ${cacheHitRate}%`);
  console.log(`  Total Cost (7d): $${totalCost.toFixed(4)}`);
  console.log(`  Projected Monthly: $${(totalCost * 30 / 7).toFixed(2)}`);
}

// Run report
generateReport().catch((error) => {
  console.error("Error generating report:", error);
  process.exit(1);
});
